Spelling checks
cfwheels/cfwheels pull request #1313
Opened 2023-11-05 19:36 UTC by MvdO79

https://github.com/cfwheels/cfwheels/issues/1159

2023-11-05 20:49 UTC, bpamiri requested changes

2023-11-05 20:49 UTC, bpamiri commented on wheels/tests/view/text/excerpt.cfc
> +		r = "[more]testing the excerpt view helper to see if[more]";
@MvdO79 can you revert this one. This is causing this test to fail which is failing the PR.

2023-11-05 23:33 UTC, MvdO79 commented
All tests are passed now!

2023-11-06 01:27 UTC, bpamiri approved these changes

2023-11-06 01:27 UTC, merged

2023-11-06 01:28 UTC, bpamiri commented
Awesome work @MvdO79. This was a huge bunch of changes.

2023-11-06 11:24 UTC, MvdO79 commented
Glad to help!